# Generated by Django 4.0.4 on 2022-10-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacterialdiseases',
            name='hosts',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bacterialdiseases',
            name='symptoms',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fungaldiseases',
            name='hosts',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fungaldiseases',
            name='symptoms',
            field=models.CharField(max_length=1000),
        ),
    ]
