# Generated by Django 4.0.4 on 2022-10-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0002_alter_bacterialdiseases_hosts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdhaarNo', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=100)),
                ('crop_season', models.CharField(max_length=12)),
                ('crop', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pest_or_fert', models.CharField(max_length=100)),
            ],
        ),
    ]
