# Generated by Django 4.0.4 on 2022-10-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0003_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField()),
                ('crop_name', models.CharField(max_length=50)),
                ('crop_year', models.IntegerField()),
                ('cr_ex', models.DecimalField(decimal_places=3, max_digits=4)),
                ('crop_season', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='AdhaarNo',
            new_name='farmerid',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='crop_season',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='pest_or_fert',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmland',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='pesticides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fert_or_pest', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plantdiseases.crops')),
            ],
        ),
        migrations.CreateModel(
            name='farming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plantdiseases.crops')),
                ('farmer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plantdiseases.farmer')),
            ],
        ),
    ]
