# Generated by Django 4.0.4 on 2022-10-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0006_alter_farmer_farmland'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='phone_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
