# Generated by Django 4.0.4 on 2022-10-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0007_farmer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticides',
            name='crop_id',
            field=models.IntegerField(),
        ),
    ]
