# Generated by Django 4.0.4 on 2022-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0012_alter_pesticides_crop_id_alter_pesticides_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticides',
            name='crop_id',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pesticides',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
