# Generated by Django 4.0.4 on 2022-10-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0013_alter_pesticides_crop_id_alter_pesticides_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticides',
            name='crop_id',
        ),
        migrations.RemoveField(
            model_name='pesticides',
            name='price',
        ),
    ]
