# Generated by Django 4.0.4 on 2022-10-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0014_remove_pesticides_crop_id_remove_pesticides_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticides',
            name='crop_id',
            field=models.IntegerField(null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='pesticides',
            name='price',
            field=models.IntegerField(null=1),
            preserve_default=1,
        ),
    ]
