# Generated by Django 4.0.4 on 2022-10-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0017_alter_crops_crop_id_alter_crops_crop_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticides',
            name='crop_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pesticides',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
