# Generated by Django 4.0.4 on 2022-10-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0019_alter_crops_crop_id_alter_crops_crop_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='cr_ex',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
