# Generated by Django 4.0.4 on 2022-10-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantdiseases', '0020_alter_crops_cr_ex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farming',
        ),
    ]
